language: python
os: linux
python:
  - "3.7"
# Setup anaconda, see https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - sed -i "s/defaults::python.*/defaults::python=$TRAVIS_PYTHON_VERSION/" environment.yml
  - conda env create -n env_name --file environment.yml
  - source activate env_name
  - python setup.py install;
script:
  - set -x
  - python --version
  - which minos
  - ls $(dirname $(which minos))/..
  - echo "BLAHBLAHBLAH"
  - python -c "from minos import __version__; print(__version__);"
  - minos -h
