language: python
os: linux
python:
  - "3.7"
# Setup anaconda, see https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - sed -i "s/defaults::python.*/defaults::python=$TRAVIS_PYTHON_VERSION/" environment.yml
  - conda env create -n env_name --file environment.yml
  - source activate env_name
  - python setup.py bdist_wheel;
  - pip install --no-deps dist/*whl
  - ls /home/travis/miniconda3/envs/env_name/lib/python3.7/site-packages/minos/*
  - ls /home/travis/miniconda3/envs/env_name/envs/mikado.yaml
script:
  # - set -x
  - python --version
  - which minos
  - ls $(dirname $(which minos))
  - ls $(dirname $(which minos))/../lib/python3.7/site-packages
  - ls $(dirname $(which minos))/../etc
  - echo "BLAHBLAHBLAHx"
  - python -c "from minos import __version__; print(__version__);"
  - minos -h
  - install_cpc2 .
  - export PATH=$PATH:$(pwd)/CPC2-beta/bin
  - export CPC_HOME=$(pwd)/CPC2-beta
  - ls -l $CPC_HOME/bin
  - CPC2.py -h
  - mikado -h
  # - wget https://zenodo.org/record/3906678/files/sample_data.tar.gz?download=1 -O sample_data.tar.gz
  - wget https://zenodo.org/record/3908201/files/sample_data.tar.gz?download=1 -O sample_data.tar.gz
  - tar xvzf sample_data.tar.gz
  - wget https://busco-data.ezlab.org/v4/data/lineages/arthropoda_odb10.2019-11-20.tar.gz -O arthropoda_odb10.tar.gz
  - tar xvzf arthropoda_odb10.tar.gz
  - ls arthropoda_odb10
  - cp -v sample_data/input_config/* .
  - cp -v $(dirname $(which minos))/../etc/minos_config.yaml.example .
  - ls -l .
  - minos configure --no_drmaa --scheduler NONE --use_conda --config-file minos_config.yaml.example -o minos_test_run --external external.yaml --external-metrics external_metrics.txt --use-tpm-for-picking --genus-identifier CIS --annotation-version EIv1 --busco-level p,t --busco-genome-run $(pwd)/sample_data/busco_genome/run_insecta_odb10 --busco-lineage $(pwd)/arthropoda_odb10 list.txt scoring_template.yaml sample_data/genome/scaffold_6.fa
  - minos run --no_drmaa --scheduler NONE --use_conda -o minos_test_run
  # minos configure --mikado-container $MIKADO -o ${RUN_DIR} --external external.yaml --external-metrics external_metrics.txt $TPM_FOR_PICKING --genus-identifier ABC --annotation-version EIv2 --busco-lineage /ei/workarea/group-pb/BUSCO_DATABASES/odb10/embryophyta_odb10 $INPUT_MODELS $SCORING_TEMPLATE Melia_azedarach.genome.uc.fasta
