language: python
os: linux
python:
  - "3.7"
# Setup anaconda, see https://gist.github.com/dan-blanchard/7045057
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - sed -i "s/defaults::python.*/defaults::python=$TRAVIS_PYTHON_VERSION/" environment.yml
  - conda env create -n env_name --file environment.yml
  - source activate env_name
  - python setup.py install;
script:
  # - set -x
  - python --version
  - which minos
  - ls $(dirname $(which minos))/../lib/python3.7/site-packages
  - ls $(dirname $(which minos))/../etc
  - echo "BLAHBLAHBLAH"
  - python -c "from minos import __version__; print(__version__);"
  - minos -h
  - install_cpc2 .
  - export PATH=$PATH:$(pwd)/CPC2-beta/bin
  - export CPC_HOME=$(pwd)/CPC2-beta
  - ls -l $CPC_HOME/bin
  - CPC2.py -h
  - wget https://zenodo.org/record/3906678/files/sample_data.tar.gz?download=1 -O sample_data.tar.gz
  - tar xvzf sample_data.tar.gz
  - cp -v sample_data/input_config/* .
  - cp -v $(dirname $(which minos))/../etc/minos_config.yaml .
  - ls -l .
