paths:
  augustus_config_data: "/usr/local/config"
params:
  mikado:
    prepare: "--minimum-cdna-length 100"
    compare:
        index: "--index"
        transcripts: "--extended-refmap"
        proteins: "--exclude-utr --extended-refmap"
    serialise: ""
    pick: ""
  gffread:
    blastp: ""
    blastx: ""
    default: ""
    final: ""
  cpc2: "-r"
  kallisto:
    index: ""
    quant: "-b 100" 
  blast:
    makeblastdb: "-dbtype prot"
    blastp: "-max_target_seqs 1 -evalue 1e-5"
    blastx: "-max_target_seqs 1 -evalue 1e-5"
    tophit:
      pident_threshold: 0.0
      qcov_threshold: 0.0
  genometools:
    check: "gff3 -sort -tidy -retainids yes -addids no"
    sort: "gff3 -sort -tidy -retainids yes"
  prinseq: "-min_len 1 -line_width 70"
  busco:
    proteins_prepare: "--offline --limit 4"
    proteins_final: "--offline --limit 4"
    transcripts_prepare: "--offline --limit 4"
    transcripts_final: "--offline --limit 4"
    genome: "--offline --limit 4"

misc:
  min_cds_length: 30
  busco_max_copy_number: 4

program_calls:
  mikado: "singularity exec {container} mikado {program}"
  gffread: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img gffread"
  cpc2: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img CPC2.py"
  kallisto: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img kallisto {program}"
  blast: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img {program}"
  genometools: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img gt"
  prinseq: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img prinseq-lite.pl"
  busco: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.busco.img busco"
  copy: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.busco.img cp -r"
  bedtools:
    coverageBed: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img coverageBed"
  time: "/usr/bin/time -v"

collapse_metrics_thresholds:
  repeat_associated: "{te_score} >= 0.4"
  # predicted_gene will also depend on classification status, but this is currently not implemented
  predicted_gene: "{hom_acov_score} < 0.3 and {cpc_score} < 0.25"
  hi_confidence: "{classification} == 1 or {hom_acov_score} >= 0.8 or ({hom_acov_score} >= 0.6 and {transcript_score} >= 0.4)"
  # discard will also depend on classification status, but this is currently not implemented
  discard: "{protein_score} == 0 and {transcript_score} == 0 and {hom_acov_score} == 0 and ({expression_score} < 0.3 or {short_cds} == 1)"
  #repeat_associated: "te_score ge 0.4"
  #predicted_gene: "hom_acov_score lt 0.3 & cpc_score lt 0.25"
  #hi_confidence: "classification eq 1 | hom_acov_score ge 0.8 | (hom_acov_score ge 0.6 & transcript_score ge 0.4)"
  #discard: "protein_score eq 0 & transcript_score eq 0 & hom_acov_score eq 0 & expression_score lt 0.3"
