gmc_container: "/ei/software/cb/containers/gmc/x86_64/Singularity.img"

tools:
  time: "/usr/bin/time -v"

resources:

params:
  mikado:
    prepare: "--minimum-cdna-length 100"
    compare:
        index: "--index"
        transcripts: "--extended-refmap"
        proteins: "--exclude-utr --extended-refmap"
    serialise: ""
    pick: "-lv DEBUG"
  gffread:
    blastp: "-y"
    blastx: "-W -x"
    default: "-W"
  cpc2: "-r"
  kallisto:
    index: ""
    quant: "-b 100" 
  blast:
    makeblastdb: "-dbtype prot"
    blastp: "-max_target_seqs 1 -evalue 1e-5"
    blastx: "-max_target_seqs 1 -evalue 1e-5"
    tophit:
      pident_threshold: 0.0
      qcov_threshold: 0.0
  genometools:
    check: "gff3 -sort -tidy -retainids yes -addids no"
    sort: "gff3 -sort -tidy -retainids yes"
  prinseq: "-min_len 1 -line_width 70"

program_calls:
  mikado: "singularity exec {container} mikado {program}"
  gffread: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img gffread"
  cpc2: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img CPC2.py"
  kallisto: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img kallisto {program}"
  blast: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img {program}"
  genometools: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img gt"
  prinseq: "singularity exec /ei/software/cb/containers/gmc/x86_64/Singularity.img prinseq-lite.pl"

metrics_collapse:
  check_thresholds:
    classification:
      repeat_associated: "te_score ge 0.4"
      predicted_gene: "hom_acov_score lt 0.3 & cpc_score lt 0.25"
    hi_confidence: "classification eq 1 | hom_acov_score ge 0.8 | (hom_acov_score ge 0.6 & transcript_score ge 0.4)"
    discard: "protein_score eq 0 & transcript_score eq 0 & hom_acov_score eq 0 & expression_score lt 0.3"
      


